base_negative = "(photo:1.2), photographic, (twins), (double), (too many limbs), (deformed, distorted, disfigured:1.3), (eyes to camera), (looking at camera), (saturated) (grain) (deformed) (lowres) (lowpoly) (CG) (3d) (blurry) (out-of-focus) (depth_of_field) (duplicate) (watermark) (label) (signature) (text) (cropped) Easynegative_promptative, sexy, naked, picture in picture, frame, multiple people, off screen, (deformed, distorted, disfigured:1.3), (photo photography photograph) (saturated) (grain) (deformed) (poorly drawn) (sexy)"

styles = [
    {
        "id": "1",
        "clientIndex": 1,
        "title": "Ink Intensity",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "line art sketch",
        "backpad": "detailed, (line art,:1.3), (intricate details), b&w, black and white , pen art, cinematic, rule of thirds",
        "lora": "",
        "lora_weight": 0.4,
        "samplerName": "DPM++ SDE Karras",
        "steps": "20",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 1.0,
        "monochrome": True,
    },
    {
        "id": "16",
        "clientIndex": 2,
        "title": "Dynamic Simplicity",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "A cinematic storyboard",
        "backpad": "Cinematic, Noir, Artstyle Graffiti, Detailed, (Pencil Art:0.8), (Ink Art:1.1), Sketching, Monochromatic, Harsh Lighting",
        "lora": "sketch_for_art_examination",
        "lora_weight": 0.4,
        "samplerName": "DPM2 a",
        "steps": "22",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": True,
    },
    {
        "id": "5",
        "clientIndex": 3,
        "title": "Sweeping Elegance",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "digital art, (digital painting:1.2), (colour:1.2), (sketch:0.3), (fast sketch:0.4), hand drawn, pixlineart, drawing",
        "backpad": "comic art, 4k,",
        "lora": "Pixel_Lineart",
        "lora_weight": 0.1,
        "samplerName": "DPM++ 3M SDE Exponential",
        "steps": "22",
        "cfgScale": "7.5",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.7,
        "monochrome": False,
    },
    {
        "id": "59",
        "clientIndex": 4,
        "title": "Ethereal Washes",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "A cinematic storyboard",
        "backpad": "Artstyle Impressionist, Watercolor, Sketching, Detailed, high budget Hollywood production",
        "lora": "Pixel_Lineart",
        "lora_weight": 0.8,
        "samplerName": "DPM++ SDE Karras",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 1.0,
        "monochrome": False,
    },
    {
        "id": "91",
        "clientIndex": 5,
        "title": "Vibrant Vectorcraft",
        "pos": " [lora], [frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad],",
        "negativePrompt": base_negative,
        "frontpad": "A cinematic storyboard, (colours:1.2), caricature",
        "backpad": "Artstyle Impressionist, (vector art:1.1), (line art:1.1), Sketching",
        "lora": "rough_sketch_xl_v2",
        "trigger_words": "rough sketch",
        "lora_weight": 0.1,
        "samplerName": "DPM++ SDE Karras",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.6,
        "monochrome": False,
    },
    {
        "id": "2",
        "clientIndex": 6,
        "title": "Vivid Portraiture",
        "pos": " [lora], [frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "a storyboard image",
        "backpad": "charcoal on paper, Rough sketch, candid, ink and water, (intricate details), b&w, black and white , pen art, cinematic framing , rule of thirds, broad stroke, stick figures, draft",
        "lora": "rough_sketch_xl_v2",
        "lora_weight": 0.6,
        "samplerName": "Euler a",
        "steps": "22",
        "cfgScale": "8",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": True,
    },
    {
        "id": "68",
        "clientIndex": 7,
        "title": "Everyday Vibes",
        "pos": "[lora], [frontpad], a [camera] shot, of [prompt] in [scene_description], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "A colour cinematic storyboard, sketch, drawing",
        "backpad": "Cinematic, Digital Art, Watercolor, Sketching, Detailed, pixlineart, ",
        "lora": "Pixel_Lineart",
        "lora_weight": 0.2,
        "samplerName": "DPM++ 2M Karras",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": False,
    },
    {
        "id": "82",
        "clientIndex": 8,
        "title": "Stellar Sketch",
        "pos": "[lora], [frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad]",
        "negativePrompt": base_negative + " (sepia)",
        "frontpad": "A cinematic storyboard, (rough sketch:0.5), (colour:1.1)",
        "backpad": "Artstyle Impressionist, (Watercolor:0.4), pen art, Sketching, vector art, duochromatic, high budget Hollywood production",
        "lora": "rough_sketch_xl_v2",
        "lora_weight": 0.5,
        "samplerName": "DPM++ SDE Karras",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": False,
    },
    {
        "id": "48",
        "clientIndex": 9,
        "title": "Dynamic Scenes",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "A cinematic storyboard",
        "backpad": "realism, Cinematic, Noir, Sketching, Pencil Art, Shading, Monochromatic,  ((vector art)),  Detailed, high budget Hollywood production, rough sketch",
        "lora": "rough_sketch_xl_v2",
        "lora_weight": 0.4,
        "samplerName": "DPM++ SDE Karras",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": True,
    },
    {
        "id": "53",
        "clientIndex": 10,
        "title": "City Chronicles",
        "pos": "[lora], [frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "Cinematic, black and white, (Line Art:1.3), Pencil Art,(vector art:1.2) Sketching, Detailed, A cinematic storyboard",
        "backpad": "high budget Hollywood production",
        "lora": "sketch_for_art_examination",
        "lora_weight": 0.2,
        "samplerName": "DPM++ 3M SDE Exponential",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": True,
    },
    {
        "id": "99",
        "clientIndex": 11,
        "title": "Illustrated Detail",
        "pos": "[lora], [frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "line art, sketch drawing,",
        "backpad": "detailed, (line art,:1.3), (intricate details), b&w, black and white , pen art, cinematic, rule of thirds",
        "lora": "sketch_for_art_examination",
        "lora_weight": 0.4,
        "samplerName": "DPM++ SDE Karras",
        "steps": "20",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": True,
    },
    {
        "id": "100",
        "clientIndex": 12,
        "title": "Dark Narrative",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [lora], [backpad]",
        "negativePrompt": base_negative,
        "frontpad": "A cinematic storyboard",
        "backpad": "Cinematic, Noir, Cyberpunk, Artstyle Graffiti, Detailed, Pencil Art, Sketching, Monochromatic, high budget Hollywood production",
        "lora": "sketch_it",
        "lora_weight": 0.4,
        "samplerName": "DPM++ SDE",
        "steps": "28",
        "cfgScale": "7",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.7,
        "monochrome": True,
    },
    {
        "id": "101",
        "clientIndex": 13,
        "title": "Linear Perspective",
        "pos": "[frontpad], a [camera] shot, of [prompt], in [scene_description], [backpad], [lora]",
        "negativePrompt": base_negative,
        "frontpad": "digital art, digital painting, sketch style, fast sketch, hand drawn,",
        "backpad": "(comic art:1.1), cinematic framing, 4k",
        "lora": "sketch_style",
        "lora_weight": 1,
        "samplerName": "DPM++ 3M SDE Exponential",
        "steps": "22",
        "cfgScale": "7.5",
        "width": "1360",
        "height": "768",
        "model": "sd_xl_base_1.0",
        "embeddingStrength": 0.8,
        "monochrome": False,
    },
]

loras = [
    {
        "lora": "asian_line",
        "trigger_words": "storyboard, sketch"
    },
    {
        "lora": "Pencil_Sketch-06R",
        "trigger_words": "pencil sketch"
    },
    {
        "lora": "Pixel_Lineart",
        "trigger_words": "pixlineart, sketch, drawing"
    },
    {
        "lora": "rough_sketch_xl_v2",
        "trigger_words": ""
    },
    {
        "lora": "sketch_for_art_examination",
        "trigger_words": "sketch for art examination"
    },
    {
        "lora": "sketch_it",
        "trigger_words": ""
    },
    {
        "lora": "sketch_style",
        "trigger_words": "sketch_style"
    },
    {
        "lora": "Lineart_v2",
        "trigger_words": "lineartlora"
    },
    {
        "lora": "Azure_Sketch_Illustration",
        "trigger_words": "ArsMJStyle, AzureSketch"
    },
    {
        "lora": "novuschroma43_style",
        "trigger_words": "novuschroma43 style"
    },
    {
        "lora": "goro-fujita-sdxl-v1-000062",
        "trigger_words": "a digital illustration, in the style of goro-fujita"
    },
    {
        "lora": "Fresh_Ideas",
        "trigger_words": "FRESHIDEAS Illustration No. 12"
    },
    {
        "lora": "fresh_ideas_2",
        "trigger_words": "XCYP Sunshine Illustration"
    },
    {
        "lora": "AQUAinked_XL",
        "trigger_words": "illustration  on a white background"
    },    
]